### PR TITLE
Fix all metadata for 3.7 and missing 3.8 titles

### PR DESCRIPTION
**Pull request by ppeble**
Fixes all metadata for v3.7 and 3.8. Turns out a missed a few sub-directories in my previous 3.8 work! Whoops!

Summary:

* Updates all metadata so that titles/navigation fully work in 3.8 and 3.7
* Updates references to `$AESproductName` to be `Emissary`
* Removes references to `$productName$` in 3.7 and 3.8 and replaces it with `Emissary`
* Removes references to `$OSSProductName$` in 3.7 and 3.8
* Fixes a lot of references to `$versionTwoX` in 3.7 and some in 3.8
* Updates any references in 3.7 and 3.8 of `Emissary-ingress` to just `Emissary`

There are still a lot of issues in both 3.8 and 3.7...lots of references to variables in places that I skipped to keep my scope down. But now 3.8 and 3.7 should have all navigation working with no visual bugs or missing links.

### CODE REVIEW

**Review by AliceProxy — APPROVED** [review]

**Comment by kflynn** [comment]
Thanks @ppeble !! 🙂

**Review by kflynn — APPROVED** [review]
Looks good! 🙂

**Review by kflynn — CHANGES_REQUESTED** [review]
Oh whoops, I spoke too soon – 

`$AESproductName` should always be "Ambassador Edge Stack", I think.
`$OSSproductName` should always be Emissary. 

and "the Emissary" is now almost always wrong (it used to be "the Emissary-ingress" which... still wrong so I don't know why that was there 😛). 

Sorry about that! 😐

**Comment by ppeble** [comment]
> Oh whoops, I spoke too soon –
> 
> `$AESproductName` should always be "Ambassador Edge Stack", I think. `$OSSproductName` should always be Emissary.
> 
> and "the Emissary" is now almost always wrong (it used to be "the Emissary-ingress" which... still wrong so I don't know why that was there 😛).
> 
> Sorry about that! 😐

Oh! So do we still want references to `Ambassador Edge Stack`? I was figuring that we wanted to remove references to it since it was a paid product, not something as part of Emissary OSS. Is that not true?

I will go through and fix the `the Emissary` parts, that's a good catch!

**Comment by kflynn** [comment]
Well, I think it might make sense to leave the "What's the difference between Emissary and Ambassador Edge Stack?" page around. In other places, it likely makes sense to trash them...

In any case, replacing `$AESproductName` with Emissary is very unlikely to be the right thing. 😉

**Comment by ppeble** [comment]
I am closing this MR so that I can start over. I think I can pull a lot of the changes for 3.7 and 3.8 into a separate branch. The other changes are too difficult/time consuming to undo. Let me regroup and get back to you.

**Pull request closed without merging**
